
import React, { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import GlassMorphism from './ui/GlassMorphism';

const DisclaimerPopup = () => {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    // Check if user has already seen the disclaimer
    const hasSeenDisclaimer = localStorage.getItem('hasSeenDisclaimer');
    
    if (!hasSeenDisclaimer) {
      // Show popup after a short delay for better UX
      const timer = setTimeout(() => {
        setIsOpen(true);
      }, 1000);
      
      return () => clearTimeout(timer);
    }
  }, []);

  const handleAgree = () => {
    // Save to localStorage to prevent showing again
    localStorage.setItem('hasSeenDisclaimer', 'true');
    setIsOpen(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in">
      <GlassMorphism 
        className="relative max-w-md w-full p-6 overflow-hidden" 
        variant="dark"
        intensity="medium"
      >
        {/* Close button */}
        <button 
          onClick={handleAgree} 
          className="absolute top-3 right-3 p-1 rounded-full bg-black/20 text-white/80 hover:bg-black/30 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>
        
        {/* Title with gradient effect */}
        <h2 className="font-bold text-2xl mb-4 text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
          Welcome to Learn Any Skill GPT
        </h2>
        
        {/* Content with stylized text */}
        <div className="space-y-4 mb-6">
          <p className="text-white/90 leading-relaxed">
            By using this AI-powered learning platform, you acknowledge that:
          </p>
          
          <ul className="space-y-2 text-white/80">
            <li className="flex items-start gap-2">
              <span className="inline-block w-1.5 h-1.5 rounded-full bg-blue-400 mt-2"></span>
              <span>Content is generated by AI and may require verification</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="inline-block w-1.5 h-1.5 rounded-full bg-purple-400 mt-2"></span>
              <span>Your interactions help improve the platform</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="inline-block w-1.5 h-1.5 rounded-full bg-blue-400 mt-2"></span>
              <span>Usage is subject to our terms and privacy policy</span>
            </li>
          </ul>
        </div>
        
        {/* Interactive Button */}
        <div className="flex justify-center">
          <Button
            onClick={handleAgree}
            className={cn(
              "relative overflow-hidden group w-full py-6 text-lg font-medium rounded-xl",
              "bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700",
              "transition-all duration-300 transform hover:scale-[1.02] active:scale-[0.98]"
            )}
          >
            <span className="relative z-10">I Agree</span>
            <span className="absolute inset-0 w-full h-full bg-white/20 transform scale-x-0 group-hover:scale-x-100 transition-transform origin-left"></span>
          </Button>
        </div>
      </GlassMorphism>
    </div>
  );
};

export default DisclaimerPopup;
